# Generated by Django 2.1.7 on 2019-02-24 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noOfVideos', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date', models.DateField()),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive', models.BooleanField()),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploader', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videoCategory1', to='api.Categories')),
                ('category2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videoCategory2', to='api.Categories')),
                ('category3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videoCategory3', to='api.Categories')),
                ('category4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videoCategory4', to='api.Categories')),
                ('category5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videoCategory5', to='api.Categories')),
                ('videoId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='categoryVideoId', to='api.Video')),
            ],
        ),
        migrations.AddField(
            model_name='likes',
            name='videoId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likeVideoId', to='api.Video'),
        ),
        migrations.AddField(
            model_name='comments',
            name='videoId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentVideoId', to='api.Video'),
        ),
    ]
