# Generated by Django 2.1.7 on 2019-02-24 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190224_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='noOfVideos',
        ),
        migrations.AlterField(
            model_name='videocategory',
            name='category2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vc2', to='api.Categories'),
        ),
        migrations.AlterField(
            model_name='videocategory',
            name='category3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vc3', to='api.Categories'),
        ),
        migrations.AlterField(
            model_name='videocategory',
            name='category4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vc4', to='api.Categories'),
        ),
        migrations.AlterField(
            model_name='videocategory',
            name='category5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vc5', to='api.Categories'),
        ),
    ]
