# Generated by Django 2.1.7 on 2019-02-24 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190224_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='publisheriD',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='videocategory',
            name='category1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vc1', to='api.Categories'),
        ),
    ]
