# Generated by Django 2.1.7 on 2019-02-24 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190224_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RenameField(
            model_name='publisher',
            old_name='userId',
            new_name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
